project/config/routes.rb
Rails.application.routes.draw do
  get 'patients/show'

  root 'homes#index'

  get 'homes/index'

  get 'homes/users_index' => 'homes#users_index'

  get 'homes/receptionists_index' => 'homes#receptionists_index'

  get 'homes/create_doctor' => 'homes#create_doctor'

  get 'homes/doctors_index' => 'homes#doctors_index'

  get 'homes/:id/edit' => 'homes#edit'

  get 'homes/:id/show' => 'homes#show'

  get 'prescriptions/:id/edit' => 'prescriptions#edit'

  delete 'homes/:id' => 'homes#destroy' 

  patch 'homes/users_update/:id' => 'homes#update'

  patch 'prescriptions/prescriptions_update/:id' => 'prescriptions#update'

  delete 'prescriptions/:id' => 'prescriptions#destroy'

  get 'patients/:id/edit' => 'patients#edit'

  patch 'patients/patient_update/:id' => 'patients#update'
  
  devise_for :users

end

project/app/models/patient.rb
class Patient < ActiveRecord::Base
	# has_one :user
	has_one :prescription
end

project/app/models/prescription.rb
class Prescription < ActiveRecord::Base
	belongs_to :user
	belongs_to :patient
end

project/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :prescriptions
end

project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

project/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :user_all
  def index
    @prescriptions = Prescription.all
  end

  def doctors_index	
    @users = @users.where("role = ?","doctor")
  end

  def receptionists_index
    @users = @users.where("role = ?","receptionist")
  end

  def edit
    @user = User.find(params[:id])
    render :partial => 'edit'
  end

  def destroy  
    @user = User.where("id = ?",params[:id]).first
    # if @user.present?
       # @user.destroy
    render text: "success"
    # end
  end

  def update
    user = User.find(params[:id])
    user.update_attributes(user_params)
    render text: "success"
  end

  def show
    @user = User.find(params[:id])
  end



  private
    def user_all
  	 @users = User.all
    end

    def user_params
      params.require(:user).permit(:name, :sex, :phone, :email)
    end
end

project/app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def show
  	@patient = Patient.find(params[:id])
  end
  def edit
    @patient = Patient.find(params[:id])
  end
  def update
    patient = Patient.find(params[:id])
    patient.update_attributes(patient_params)
    redirect_to "/homes/index"
  end
private
  def patient_params
      params.require(:patient).permit(:name, :sex, :phone, :email,:disease_type)
  end
end

project/app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
	before_action :prescriptions_all
  def edit
    @prescription = Prescription.find(params[:id])
  end

  def update
    prescription = Prescription.where("id = ?",params[:id]).first
    prescription.update_attributes(prescription_params)
    redirect_to "/homes/index"
  end
  def destroy
    @prescription = Prescription.where("id = ?",params[:id]).first
    @prescription.destroy if @prescription.present?
    redirect_to "/homes/index"
  end

 private 
 def prescriptions_all
  	 @prescription = Prescription.all
    end
  def prescription_params
     params.require(:prescription).permit(:name, :med_type)
  end
end

project/app/helpers/application_helper.rb
module ApplicationHelper
end

project/app/helpers/home_helper.rb
module HomeHelper
end

project/app/helpers/patients_helper.rb
module PatientsHelper
end

project/app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

project/app/views/homes/_edit.html.erb
<%= form_for (@user), url: "/homes/users_update/#{@user.id}",:id =>"my_form" do |f| %>
<div class="field">
  <%= f.label :Email %>:
  <%= f.email_field :email %>
</div>
<div class="field">
  <%= f.label :Name %>:
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :sex %>
  <%= f.radio_button :sex, 'male', :checked => true %> male
  <%= f.radio_button :sex, 'female' %> female
</div>
<div class="field">
  <%= f.label :Phone %>:
  <%= f.text_field :phone %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

project/app/views/homes/destroy.js.erb
$('#delete_doctor_ajax').bind('ajax:success', function() {  
        $(this).closest('tr').fadeOut();
});  
$('#delete_receptionist_ajax').bind('ajax:success', function() { 
        $(this).closest('tr').fadeOut();

});  

project/app/views/homes/doctors_index.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<%= link_to "Invite Doctor" %>
<table class= "table table-hover table-striped">
  <tr>
    <th>Name</th>
    <th>Email id</th>
    <th>Phone Number</th>
    <th>Sex</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @users.each do |u| %>
    <tr id = "user_<%= u.id%>">
      <td><%= u.name %></td>
      <td><%= u.email %></td>
      <td><%= u.phone %></td>
      <td><%= u.sex %></td>
      <div class="container">
        <div class="modal fade" id="myModal" role="dialog">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Edit <%= u.name %></h4>
              </div>
              <div class="modal-body">
                <img src="/assets/source.gif" style="height:30px;width:30px;text-align: center;">
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              </div>
            </div>     
          </div>
        </div>
      </div>
      <% if current_user.role == "admin" || current_user.id == u.id %>
        <td>
          <%= link_to "#{u.id}/show" do %>
            <span class="glyphicon glyphicon-user"></span>
          <% end %>
        </td>
        <td>
          <%= link_to "javascript:void(0)",'data-toggle'=>"modal", 'data-target'=>"#myModal",:id => "modal_edit","data-id" => u.id do %>
            <span class="glyphicon glyphicon-pencil"></span>
          <% end %>
        </td>
        <td>
          <%= link_to "javascript:void(0)",method: :delete,:class => "delete_doctor_ajax","data-id" => u.id  do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

<script>
  $("#modal_edit").click(function(e){ 
      var id = $(this).data('id'); 
      $.ajax({ 
        type: 'GET',
        url: id+"/edit",
        success: function(data){
          $(".modal-body").html(data);
      }, 
      error: function(data){ alert('error'); } })
  });
  $(".delete_doctor_ajax").click(function(){ 
    var id = $(this).data('id'); 
    $.ajax({ 
    type: 'DELETE',
    url: "/homes/"+id,
    success: function(data){
      $("#user_"+id).fadeOut(1000);
  }, 
  error: function(data){ alert('error'); } })
  });
</script>

project/app/views/homes/edit.html.erb
<%= form_for (@user), url: "/homes/doctors_update/#{@user.id}" do |f| %>
<div class="field">
  <%= f.label :Email %>:
  <%= f.email_field :email %>
</div>
<div class="field">
  <%= f.label :Name %>:
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :sex %>
  <%= f.radio_button :sex, 'male', :checked => true %> male
  <%= f.radio_button :sex, 'female' %> female
</div>
<div class="field">
  <%= f.label :Phone %>:
  <%= f.text_field :phone %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

project/app/views/homes/index.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<% if current_user.role == "admin" %>
<h1>Welcome Admin <%= link_to "homes/#{current_user.id}/show" do %>
    <span class="glyphicon glyphicon-user"></span>
<% end %></h1>
<p><%= link_to('Doctors',homes_doctors_index_path) %>
	<%= link_to('Receptionists',homes_receptionists_index_path)%>
</p>
<%else %>

<b>Logged in as : <%= current_user.name %></b><br>
<b>View Profile </b>
<%= link_to "/homes/#{current_user.id}/show" do %>
    <span class="glyphicon glyphicon-user"></span>
<% end %>

<table class= "table table-hover table-striped">
  <tr>
    <th>Sl.no</th>
  <% if current_user.role != "receptionist" %>
    <th>Type</th>
    <th>Name</th>
  <%end %>
    <th>Patient Name</th>
    <th>Doctor Name</th>
  <% if current_user.role != "receptionist" %>  
    <th></th>
    <th></th>
  <%end %>
  </tr>
  <% @prescriptions.each do |p| %>
    <tr>
      <td><%= p.id %></td>
    <% if current_user.role != "receptionist" %>
      <td><%= p.med_type %></td>
      <td><%= p.name %></td> 
    <%end %>
      <td><%=link_to "#{p.patient.name}",controller: "patients", action: "show", id: "#{p.patient.id}" %></td>  
      <td><%= p.user.name %></td>  
      <% if current_user.role == "doctor"%>
        <td>
          <%= link_to "/prescriptions/#{p.id}/edit" do %>
            <span class="glyphicon glyphicon-pencil"></span>
          <% end %>
        </td>
        <td>
          <%= link_to "/prescriptions/#{p.id}",data: {confirm: "Are you sure?"},method: :delete  do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>
<% end %>

project/app/views/homes/receptionists_index.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<%= link_to "Invite Receptionist" %>
<table class= "table table-hover table-striped">
  <tr >
    <th>Name</th>
    <th>Email id</th>
    <th>Phone Number</th>
    <th>Sex</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @users.each do |u| %>
    <tr id = "user_<%= u.id%>">
      <td><%= u.name %></td>
      <td><%= u.email %></td>
      <td><%= u.phone %></td>
      <td><%= u.sex %></td>
      <div class="container">
        <div class="modal fade" id="myModal" role="dialog">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Edit <%= u.name %></h4>
              </div>
              <div class="modal-body">
                <img src="/assets/source.gif" style="height:30px;width:30px;text-align: center;">
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              </div>
            </div>     
          </div>
        </div>
      </div>
      <% if current_user.role == "admin" %>
        <td>
          <%= link_to "#{u.id}/show" do %>
            <span class="glyphicon glyphicon-user"></span>
          <% end %>
        </td>
        <td>
          <%= link_to "javascript:void(0)",'data-toggle'=>"modal", 'data-target'=>"#myModal",:id => "modal_edit","data-id" => u.id,:remote => true do %>
              <span class="glyphicon glyphicon-pencil"></span>
          <% end %>
        </td>
        <td><%= link_to "javascript:void(0)",method: :delete,:class => "delete_receptionist_ajax","data-id" => u.id do %>
        <span class="glyphicon glyphicon-trash"></span>
        <% end %>
      <% end %>
      </td>
    </tr>
  <% end %>
</table>

<script>
  $("#modal_edit").click(function(e){ 
      var id = $(this).data('id'); 
      $.ajax({ 
        type: 'GET',
        url: ""+id+"/edit",
        success: function(data){
          $(".modal-body").html(data);
      }, 
      error: function(data){ alert('error'); } 
    })
  })

  $(".delete_receptionist_ajax").click(function(e){ 
    if(confirm("Are you sure..???")){
      var id = $(this).data('id'); 
      $.ajax({ 
        type: 'DELETE',
        url: "/homes/"+id,
        success: function(data){
        $("#user_"+id).fadeOut();
      }, 
      error: function(data){ alert('error'); } })
    }
  })
 
  $(".modal-body.modal_edit").on("submit", function(event){
    var id = $(this).data('id'); 
    alert(id);
    $.ajax({
      type: "PATCH",
      url: "homes/users_update/",
      success: function(response) {
        alert(response);
      }
    });
  })

</script>

project/app/views/homes/show.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @user.sex %>
</p>
<%= link_to "edit" do %>
   Edit <span class="glyphicon glyphicon-pencil"></span>
<% end %>

project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
	<ul>
		<% if user_signed_in? %>
		  <li>
		  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
		  </li>
		<% else %>
		  <li>
		  <%= link_to('Login', new_user_session_path)  %>  
		  </li>
		<% end %>
	</ul>
	<hr>
<%= yield %>

</body>
</html>

project/app/views/patients/edit.html.erb
<%= form_for (@patient), url: "/patients/patient_update/#{@patient.id}" do |f| %>
 <div class="field">
    <%= f.label :Name %>:
    <%= f.text_field :name %>
 </div>
 <div class="field">
    <%= f.label :Email %>:
    <%= f.email_field :email %>
 </div>
 <div class="field">
    <%= f.label :sex %>
    <%= f.radio_button :sex, 'male', :checked => true %> male
    <%= f.radio_button :sex, 'female' %> female
 </div>
 <div class="field">
    <%= f.label :Phone %>:
    <%= f.text_field :phone %>
 </div>
 <div class="field">
    <%= f.label :Disease_Type %>:
    <%= f.text_field :disease_type %>
 </div>
 <div class="actions">
    <%= f.submit %>
 </div>
<% end %>

project/app/views/patients/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @patient.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @patient.phone %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @patient.sex %>
</p>

<p>
  <strong>Disease Type:</strong>
  <%= @patient.disease_type %>
</p>
<p>
  <strong>Doctor Name:</strong>
  <%=@patient.prescription.user.name %>
</p>
<% if current_user.role == "receptionist" %>
<%= link_to "#{@patient.id}/edit" do %>
   Edit <span class="glyphicon glyphicon-pencil"></span>
<% end %>
<% end %>

project/app/views/prescriptions/edit.html.erb
<%= form_for (@prescription), url: "/prescriptions/prescriptions_update/#{@prescription.id}" do |f| %>
<div class="field">
    <%= f.label :Type %>:
    <%= f.text_field :med_type %>
 </div>
 <div class="field">
    <%= f.label :Name %>:
    <%= f.text_field :name %>
 </div>
 <div class="actions">
    <%= f.submit %>
  </div>
<% end %>